### ISSUE TITLE
Tests failing on Linux

### ISSUE THREAD

**Issue by kasbah** [domenic/svg2png#34] opened 2015-11-12 14:46 UTC
Re-tested with svg2png 2.0.0 using `npm test`.

~~~
> svg2png@2.0.0 test /home/kaspar/projects/svg2png
> mocha



  1) Scale 1.svg to 80%
  2) Scale 2.svg to 180%
  3) Omit scale argument for 3.svg
  4) No green border for 4.svg
  5) Scales 5.svg correctly despite viewBox + fixed width/height
  ✓ should pass through errors that occur while calculating dimensions
  ✓ should pass through errors about unloadable source files

  2 passing (5s)
  5 failing
~~~

Not sure how to get a more verbose output out of Mocha.

**Comment by domenic** [comment] 2015-11-12 15:54
Dupe of #9

**Closed by domenic** 2015-11-12 15:54 UTC
