### ISSUE TITLE
Error: Width or height could not be determined from either the source file or the supplied dimensions

### ISSUE THREAD

**Issue by hwclass** [domenic/svg2png#52] opened 2016-08-24 13:22 UTC
Hi all,

I have got the following error stack during converting:

$ svg2png icons.svg
C:\Users\Administrator\AppData\Roaming\nvm\v6.3.0\node_modules\svg2png\lib\svg2png.js:52
         throw new Error(stdout.replace(/\r/g, "").trim());
         ^

Error: Width or height could not be determined from either the source file or the supplied dimensions

  phantomjs://code/converter.js:36
    at processResult (C:\Users\Administrator\AppData\Roaming\nvm\v6.3.0\node_modules\svg2png\lib\svg2png.js:52:16)
    at Function.module.exports.sync (C:\Users\Administrator\AppData\Roaming\nvm\v6.3.0\node_modules\svg2png\lib\svg2png.js:22:12)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\nvm\v6.3.0\node_modules\svg2png\bin\svg2png-cli.js:35:24)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)

Thanks

Baris

**Comment by domenic** [comment] 2016-08-24 17:45
Can you supply the SVG file you are using?

Did you read the readme, which specifies that you need to supply a width or height option if your SVG file does not have appropriate dimensions embedded in it?

**Comment by subhog** [comment] 2016-09-06 10:34
I have the same error. Line:

    svg2png(svg, { width: 640, height: 640 }).then(...)


File:
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg version="1.1" width="100" height="100" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 99.864" enable-background="new 0 0 100 99.864" xml:space="preserve">
      <rect x="0" y="0" width="100" height="100" fill="#808080"/>
      <path fill="#231F20" d="M83.713,63.42c-0.307-1.176-0.998-2.188-1.795-3.023c0.539-2.354,0.832-4.801,0.832-7.314      
      C77.318,54.467,77.18,55.815,76.98,57.143"></path>
      <path fill="#231F20" d="M44.366,48.122c0,2.231-1.808,4.039-4.039,4.039s-4.039-1.807-4.039-4.039c0-2.23,1.808-4.039,4.039-4.039
      S44.366,45.892,44.366,48.122"></path>
      <path fill="#231F20" d="M63.984,48.122c0,2.231-1.809,4.039-4.039,4.039c-2.231,0-4.039-1.807-4.039-4.039
      c0-2.23,1.808-4.039,4.039-4.039C62.176,44.083,63.984,45.892,63.984,48.122"></path>
    </svg>

**Comment by domenic** [comment] 2016-09-10 21:29
Hmm, I'm unable to reproduce the issue. Here is my test file in full:

```js
"use strict";
const svg2png = require("svg2png");

const buffer = Buffer.from(`<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 99.864" enable-background="new 0 0 100 99.864" xml:space="preserve">
  <rect x="0" y="0" width="100" height="100" fill="#808080"/>
  <path fill="#231F20" d="M83.713,63.42c-0.307-1.176-0.998-2.188-1.795-3.023c0.539-2.354,0.832-4.801,0.832-7.314      
  C77.318,54.467,77.18,55.815,76.98,57.143"></path>
  <path fill="#231F20" d="M44.366,48.122c0,2.231-1.808,4.039-4.039,4.039s-4.039-1.807-4.039-4.039c0-2.23,1.808-4.039,4.039-4.039
  S44.366,45.892,44.366,48.122"></path>
  <path fill="#231F20" d="M63.984,48.122c0,2.231-1.809,4.039-4.039,4.039c-2.231,0-4.039-1.807-4.039-4.039
  c0-2.23,1.808-4.039,4.039-4.039C62.176,44.083,63.984,45.892,63.984,48.122"></path>
</svg>`);

svg2png(buffer, { width: 640, height: 640 }).then(output => {
    console.log("output retrieved");
})
.catch(e => console.error(e));
```

I'm going to add your file as another test and close this issue, but happy to reopen if we can get some clarity...

**Closed** 2016-09-10 21:41 UTC

**Comment by subhog** [comment] 2016-09-10 23:23
Sorry, I've posted a solution but now for some reason it's not here – I must have had some connection malfunction. The problem, at least for me, was that I've passed the svg as string, not buffer. This line works without problems:

    svg2png(new Buffer(svg), { width: 640, height: 640 }).then(...)

**Comment by domenic** [comment] 2016-09-10 23:24
Ah interesting, maybe we should add a better error in that case.

**Comment by kolya182** [comment] 2018-03-02 03:07
Running `svg2png 546241.svg` in terminal:
`Image source`: https://storage.googleapis.com/ck-kitty-image/0x06012c8cf97bead5deae237070f9587f8e7a266d/546241.svg
`Error: Width or height could not be determined from either the source file or the supplied dimensions
  phantomjs://code/converter.js:49 in onLoadFinished`
